FROM docker.io/rockylinux/rockylinux:8.4

ENV LENA_HOME /usr/local/lena
# create LENA HOME
RUN mkdir -p /usr/local/lena
# copy LENA install files
COPY web-dist/target/lena-work/*.tar.gz web-containerization/install.sh web-containerization/entrypoint.sh ${LENA_ROOT}

# Insall LENA
RUN cd ${LENA_HOME} \
	&& chmod +x *.sh \
	&& ${LENA_HOME}/install.sh \
	&& rm -f ${LENA_HOME}/install.sh

WORKDIR $LENA_HOME
CMD ["./entrypoint.sh"]
