# FROM IMAGE will be changed by docker build argument
ARG FROM_IMAGE=MustInputBuildArg
FROM docker.io/${FROM_IMAGE}

ENV LENA_HOME /usr/local/lena
#ARG JDK_HOME=/usr/lib/jvm/java
#ENV JAVA_HOME ${JDK_HOME}
ENV SERVER_NAME webServer
ENV SERVICE_PORT 7180

# create LENA HOME
RUN mkdir -p /usr/local/lena
# copy LENA install files
COPY web-dist/target/lena-work/*.tar.gz web-containerization/install.sh web-containerization/entrypoint.sh ${LENA_HOME}

# Insall LENA
RUN cd ${LENA_HOME} \
	&& chmod +x *.sh \
	&& ${LENA_HOME}/install.sh \
	&& rm -f ${LENA_HOME}/install.sh

# Test Web Server
RUN ${LENA_HOME}/servers/${SERVER_NAME}/start.sh \
    && echo '::set-output name=SELECTED_COLOR::green'

WORKDIR $LENA_HOME
CMD ["./entrypoint.sh"]
