name: '[Dev] Pull Request Build Action'
on:
  push:
    branches:
      - 'dev/**'
jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          # NOTE: at now only orgs is supported
          owner: openlena
          name: lena-web
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "0.2.0-SNAPSHOT_centos7_220420145106"