name: '[Dev] Pull Request Build Action'
on:
  push:
    branches:
      - 'dev/**'
jobs:
  centos7:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      # check out repo
      - uses: actions/checkout@v2
      # setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Compile Web
      - name: Compile Web
        uses: ./web-compile/action/centos7
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      # Build Install file
      - name: Build Open LENA Web install file
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      # Get Version from maven pom.xml
      - name: Bump Version
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      # Upload install file to Github Artifact
      - name: Upload install file to Github Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Set current date as env variable
        run: echo "datetime=$(date +'%y%m%d%H%M%S')" >> $GITHUB_ENV
      # Build And Push to ghcr
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile_dev
          push: true
          build-args: |
            FROM_IMAGE=centos:7
          tags: |
            ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}_${{ env.datetime }}
      # Run conatiner for simple test
      - name: Docker Run Action
        id: dockerRunAction
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}_${{ env.datetime }}
          shell: bash
          run: |
            echo "========================="
            ${LENA_HOME}/servers/${SERVER_NAME}/start.sh
            ${LENA_HOME}/servers/${SERVER_NAME}/ps.sh
            curl localhost:7180
            if [ "$?" -eq "0" ] ; then
              RESULT=SUCCESS1
            else
              RESULT=FAIL
            fi
            echo '::set-output name=RESULT::'${RESULT}
            echo "========================="
      - name: Curl Result Check
        if: ${{ steps.dockerRunAction.outputs.RESULT != 'SUCCESS' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Command Failed [ curl localhost:7180 ]')
