name: '[Dev] Pull Request Build Action'
on:
  push:
    branches:
      - 'dev/**'
jobs:
  amazonlinux2:
    name: ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Web
        uses: ./web-compile/action/amazonlinux2
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/openlena/*" }]'
          servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
      - name: Build with Maven
        run: mvn -B package --file web-dist/pom.xml -Dcompile.os.name=${{ github.job }}
      - name: Bump Version
        id: get-version
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pom-path: web-dist
      - name: Upload install file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: web-dist/target/lena-work/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repository
        name: change github.repository string to lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and test
        id: buildAndTest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-containerization/Dockerfile_dev
          push: false
          build-args: |
            FROM_IMAGE=amazonlinux:2
          tags: ${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}
      - name: check image
        run: docker images
      - name: Docker Run Action
        id: dockerRunAction
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ steps.repository.outputs.lowercase }}:${{ steps.get-version.outputs.version }}_${{ github.job }}
          shell: bash
          run: |
            echo "test"
            echo '::set-output name=SELECTED_COLOR::${SERVER_NAME}'
            pwd
            ls -al
            curl -v localhost:7180
            echo "curl result : $?"
      - name: Check output
        run: echo "The selected color is ${{ steps.dockerRunAction.outputs.SELECTED_COLOR }}"